srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex2-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex3-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex4-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex5-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex6-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex7-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex8-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex9-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex10-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex11-1.json --cl 5
