srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex19-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex19-2.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex19-3.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex19-4.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex20-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex20-2.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex20-3.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex20-4.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex21-1.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex21-2.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex21-3.json --cl 5
srun --mem=50G --cpus-per-task=8 --gres=gpu:2 python3 dstl_train.py --config experiments/dstl_ex21-4.json --cl 5
